### ISSUE TITLE
Run pngs through some minifier

### ISSUE THREAD

**Issue by ngzhian** [chromelens/chromelens#12]

**Comment by eugenecys** [comment]
Is it to reduce page footprint? I can compress the images even more.

**Comment by ngzhian** [comment]
yup reduce the page footprint! we can reduce the size (bytes) without reducing the size (pixels)

**Comment by eugenecys** [comment]
okay minified all pngs above 10kb. Got an average of 65% reduction in size :)

dcd7445a62fe384ae95cce431445307661963c7b
