### ISSUE TITLE
Update readme with blog posts

### ISSUE THREAD

**Issue by ngzhian** [chromelens/chromelens#14]
http://briancoords.com/tech/analyzing-accessibility-chromelens/
http://www.jaredrigby.co.uk/2016/07/11/accessibility-testing-with-chromelens.html

**Comment by ngzhian** [comment]
and maybe even website too?

**Comment by eugenecys** [comment]
Why not? I think the readme can do with more content anyway. Added the blogposts and also credits for where I got the color blind info from. Also added website.
