### ISSUE TITLE
Dark Dev Tools

### ISSUE THREAD

**Issue by bennyp123** [chromelens/chromelens#2]
Howdy. I prefer the dark dev tools theme. Text contrast is too low.

**Comment by bennyp123** [comment]
<img width="454" alt="screen shot 2016-07-11 at 10 33 09 pm" src="https://cloud.githubusercontent.com/assets/1466420/16743970/78cf6962-47b7-11e6-9d93-c000be31c2fa.png">

**Comment by jin** [comment]
Thanks for raising this - I'll look into it!

**Comment by bennyp123** [comment]
Was that a pun? ;) Great extension thank you for providing this to the community!

**Comment by jin** [comment]
Implemented in 14269bf. Extension update should be ready soon.

Hope this lights up your day!
