### ISSUE TITLE
Images on the site aren’t optimized

### ISSUE THREAD

**Issue by pepelsbey** [chromelens/chromelens#3]
There are 7 images that gives 4.3 MB loading impact on your main page:

- chromelens.png: 100 × 100 pixels (Natural: 2400 × 2400 pixels)
- chromelens1.png: 400 × 271 pixels (Natural: 3000 × 2000 pixels)
- protanopiatest.png: 739 × 352 pixels (Natural: 1823 × 853 pixels)
- twittercb.png: 739 × 575 pixels (Natural: 1212 × 939 pixels)
- website_accessiblity.png: 739 × 369 pixels (Natural: 1920 × 942 pixels)
- website_protanopia.png: 739 × 355 pixels (Natural: 1920 × 906 pixels)
- website_trace.png: 739 × 336 pixels (Natural: 1920 × 855 pixels)

Even with retina support this is way too much. Please consider cutting them down, the best solution would be:

```html
<img src="chromelens.png" srcset="chromelens@2x.png 2x">
```

Where `chromelens.png` is 100 × 100 and `chromelens@2x.png` is 200 × 200 for retina screens.

**Comment by eugenecys** [comment]
Implemented in  af8209. Thanks for the feedback!

**Comment by pepelsbey** [comment]
Looks much better now! But you have a service `Thumbs.db` file in your images folder and [twittercb@2x.png](http://chromelens.xyz/images/twittercb@2x.png) is 404.
